#!/bin/sh

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

# Install the java dbus service
rm -f /usr/lib/luna/java/com.tntservices.ppbkuservice.jar
ln -s $IPKG_OFFLINE_ROOT/usr/lib/luna/java/com.tntservices.ppbkuservice.jar /usr/lib/luna/java/com.tntservices.ppbkuservice.jar
rm -f /usr/share/dbus-1/system-services/com.tntservices.ppbkuservice.service
ln -s $IPKG_OFFLINE_ROOT/usr/share/dbus-1/system-services/com.tntservices.ppbkuservice.service /usr/share/dbus-1/system-services/com.tntservices.ppbkuservice.service

# Install the upstart script
rm -f /etc/event.d/com.tntservices.ppbkuservice
cp $IPKG_OFFLINE_ROOT/etc/event.d/com.tntservices.ppbkuservice /etc/event.d/com.tntservices.ppbkuservice

exit 0
