#!/bin/sh

# Stop the service
/sbin/stop com.tntservices.ppbkuservice

# Remove the java dbus service
rm -f /usr/lib/luna/java/com.tntservices.ppbkuservice.jar
rm -f /usr/share/dbus-1/system-services/com.tntservices.ppbkuservice.service

# Remove the upstart script
rm -f /etc/event.d/com.tntservices.ppbkuservice

exit 0
