#!/bin/sh
# By Drew Phillibert 11/13/2009
# drew.phillibert@gmail.com
# TNT Services, Inc.

mount -o remount,rw /  > /tmp/null
rm -rf /tmp/Exclude  > /tmp/null
echo -e $1 > /tmp/Include
echo "Successfully built list!"
rm -rf  /tmp/null
