#!/bin/sh
# By Drew Phillibert 11-01-2009
# drew.phillibert@gmail.com
# TNT Services, Inc.

mount -o remount,rw /

if [ ! -f /opt/bin/tar ]; then
	echo -e "\nAn error occured with GNU TAR. Palm Pre Backup cannot continue!"
	exit 1
fi

if [ ! -d /media/internal/ppbackup ]; then
	mkdir /media/internal/ppbackup > /null
fi

/opt/bin/tar -cvf /media/internal/ppbackup/ppbku_$1.tar.gz --files-from=/tmp/Include --exclude-from=/tmp/Exclude  > /tmp/backup_log

if [ -f /media/internal/ppbackup/ppbku_$1.tar.gz ]; then
	echo -e "\nThe Palm Pre Backup completed successfully!"
else
	echo -e "\nThe Palm Pre Backup was not successful. Check your disk space, and try again."
	exit 1
fi

rm -rf /null
exit 0
