#!/bin/sh
# By Drew Phillibert 11-01-2009
# drew.phillibert@gmail.com
# TNT Services, Inc.

mount -o remount,rw / > /null
if [ -f /media/internal/ppbackup/ppbkusvc.tar.gz ]; then
	rm -rf /media/internal/ppbackup >/null
fi

if [ ! -f /opt/bin/tar ]; then
		ipkg-opt install tar > /null
	if [ ! -f /opt/bin/tar ]; then
		echo -e "\nAn error occured installing TAR. Palm Pre Backup cannot continue!"
		exit 1
	fi
	mkdir /media/internal/ppbackup > /null
	/opt/bin/tar -czvf /media/internal/ppbackup/ppbku.tar.gz --files-from=/tmp/Include --exclude-from=/tmp/Exclude > /null
else
	mkdir /media/internal/ppbackup > /null
	/opt/bin/tar -czvf /media/internal/ppbackup/ppbku.tar.gz --files-from=/tmp/Include --exclude-from=/tmp/Exclude > /null
fi

if [ -f /media/internal/ppbackup/ppbkusvc.tar.gz ]; then
	echo -e "\nThe Palm Pre Backup completed successfully!"
else
	echo -e "\nThe Palm Pre Backup was not successful. Check your disk space, and try again."
fi

rm -rf /null
