#!/bin/sh
# By Drew Phillibert 11-01-2009
# drew.phillibert@gmail.com
# TNT Services, Inc.

mount -o remount,rw / > /null
if [ -f $1 ]; then
	cd /
	tar -xvf $1 > /tmp/restore_log
	echo "SUCCESS: ppbku_$1.tar.gz, was successfuly restored."
	exit 0
fi
echo "ERROR: The archive is missing. Cannot continue. The restore failed."
rm -rf /null
exit 1
